version: '2'
services:
    web:
        image: nginx:1.13.9
        ports:
            - 8080:80
        volumes:
            - ..:/data
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    php:
        build: .
        volumes:
            - ..:/data
            - ./php/custom/php.ini:/usr/local/etc/php/conf.d/custom.ini
        working_dir: /data
        expose:
            - 9000
        command: php-fpm -R -y /data/docker/php/php-fpm.conf
    composer:
        image: composer:1.6.3
        volumes:
            - ..:/app
        command: install
    mysql:
        image: mysql:5.7.21
        ports:
            - 3307:3306 # avoid local mysql port busy
        volumes:
            - ./mysql/mysql.d:/etc/mysql/conf.d
            # https://stackoverflow.com/questions/39175194/docker-compose-persistent-data-mysql
            - ../dump:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_USER: "app"
            MYSQL_PASSWORD: "app"
            MYSQL_DATABASE: "app"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
